-- soc_system_md5_control_0.vhd

-- Generated using ACDS version 14.0 209 at 2025.03.28.15:46:32

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity soc_system_md5_control_0 is
	port (
		avs_s0_address   : in  std_logic_vector(3 downto 0)  := (others => '0'); --          s0.address
		avs_s0_write     : in  std_logic                     := '0';             --            .write
		avs_s0_writedata : in  std_logic_vector(31 downto 0) := (others => '0'); --            .writedata
		avs_s0_read      : in  std_logic                     := '0';             --            .read
		avs_s0_readdata  : out std_logic_vector(31 downto 0);                    --            .readdata
		clk              : in  std_logic                     := '0';             --       clock.clk
		reset            : in  std_logic                     := '0';             --       reset.reset
		mult_start       : out std_logic_vector(31 downto 0);                    -- md5_control.m_start
		mult_reset       : out std_logic_vector(31 downto 0);                    --            .m_reset
		mult_done        : in  std_logic_vector(31 downto 0) := (others => '0')  --            .m_done
	);
end entity soc_system_md5_control_0;

architecture rtl of soc_system_md5_control_0 is
	component mult_control is
		port (
			avs_s0_address   : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- address
			avs_s0_write     : in  std_logic                     := 'X';             -- write
			avs_s0_writedata : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			avs_s0_read      : in  std_logic                     := 'X';             -- read
			avs_s0_readdata  : out std_logic_vector(31 downto 0);                    -- readdata
			clk              : in  std_logic                     := 'X';             -- clk
			reset            : in  std_logic                     := 'X';             -- reset
			mult_start       : out std_logic_vector(31 downto 0);                    -- m_start
			mult_reset       : out std_logic_vector(31 downto 0);                    -- m_reset
			mult_done        : in  std_logic_vector(31 downto 0) := (others => 'X')  -- m_done
		);
	end component mult_control;

begin

	md5_control_0 : component mult_control
		port map (
			avs_s0_address   => avs_s0_address,   --          s0.address
			avs_s0_write     => avs_s0_write,     --            .write
			avs_s0_writedata => avs_s0_writedata, --            .writedata
			avs_s0_read      => avs_s0_read,      --            .read
			avs_s0_readdata  => avs_s0_readdata,  --            .readdata
			clk              => clk,              --       clock.clk
			reset            => reset,            --       reset.reset
			mult_start       => mult_start,       -- md5_control.m_start
			mult_reset       => mult_reset,       --            .m_reset
			mult_done        => mult_done         --            .m_done
		);

end architecture rtl; -- of soc_system_md5_control_0
